hibernate.connection.url=${MYSQL_URL:jdbc:mysql://localhost:3306/movie}
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.username=${MYSQL_USER:root}
hibernate.connection.password=${MYSQL_PASSWORD:mysql}
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=validate


